### ISSUE TITLE
Doesn't work on Android 6.0.1

### ISSUE THREAD

**Issue by Rudloff** [Zinggi/NoKey#30]
Hello,

I'm using Android 6.0.1 without Play services.

I tried to use NoKey 0.4 but it is stuck in the loader and I see this error in logcat:
```
06-16 14:21:20.413 26329 26329 I chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token =>", source: https://nokey.xyz/bundle.js (1)
```
This might happen because my webview is too old (Chromium 44).

**Comment by Zinggi** [comment]
Interesting.
I'm pretty sure it has nothing to do with the Android version but everything with the webview version.
But I think I can fix it easily, at least this error.
Maybe there will be other errors down the line with your version, but we'll see

**Comment by IzzySoft** [comment]
Any ETA when that next release will happen? The ETA you just gave somehow doesn't seem real :wink:

Background: [your RFP](https://gitlab.com/fdroid/rfp/issues/625) at F-Droid is stalled waiting for this.

**Comment by IzzySoft** [comment]
Jupp, saw it – thanks again! Should you eventually pick this up again, be welcome "back" to reopen that RFP. Good luck until then!
