### ISSUE TITLE
.xyz domain - tracking

### ISSUE THREAD

**Issue by Kimpfimp** [Zinggi/NoKey#31]
.xyz domain has trackers and is tracking everything that goes to and from your server as it seems.
This is a huge turn of if wanting to spread the app to users who don't have their own server.
![screenshot from 2018-06-18 19-59-05](https://user-images.githubusercontent.com/27435191/41553437-18ffb6e2-7332-11e8-8000-4dfd4b4589e4.png)
![screenshot from 2018-06-18 19-58-22](https://user-images.githubusercontent.com/27435191/41553499-3883d0fc-7332-11e8-896c-50c6b67e3c3a.png)

**Comment by Zinggi** [comment]
There are no trackers on my server, my server doesn't store anything.    
This is a false positive from easylist.   
It contains a wildcard match for all `*.xyz` websocket domains.   
I didn't know that when I purchased the domain, but the issue should really be taken to easylist.   

But what I find weird is that this was actually blocked for you, as the wildcard filter should only apply to third *party domains*. How are you running NoKey?

**Comment by Kimpfimp** [comment]
I've got NoKey on Vivaldi (which is based on Chromium)

**Comment by Zinggi** [comment]
The browser extension or the web app?
uBlock really shouldn't block the connection as it's not a third party domain, I don't know what's up with that.

In any case, I'm closing this, as I can't do anything against it.
You can work around it by putting it on the whitelist, but I didn't have to do to that (I'm also using uBlock, without any custom rules).
